### ISSUE TITLE
Acrobat Kid (Japan) graphical issues

### ISSUE THREAD

**Issue by fleroviux** [nba-emu/NanoBoyAdvance#102]
![image](https://user-images.githubusercontent.com/13669774/82122018-457b9300-9791-11ea-8e4e-51fd42509d33.png)

- black line that is flickering which should not be there
- ~~menu text is not blended properly.~~

**Comment by fleroviux** [comment]
Menu text was fixed in https://github.com/fleroviux/NanoboyAdvance/commit/c55fe50468d4538f04408b53070200ce219b6a27

**Comment by endrift** [comment]
This has to do with DMAs. mGBA had this bug too: https://github.com/mgba-emu/mgba/issues/743#issuecomment-490651362

**Comment by fleroviux** [comment]
Interesting. That is something I don't handle yet, thanks.
