### ISSUE TITLE
Lock bus during swap instruction?

### ISSUE THREAD

**Issue by fleroviux** [nba-emu/NanoBoyAdvance#148]

**Comment by GhostRain0** [comment]
https://github.com/GhostRain0/SwpTestsGBA

**Comment by GhostRain0** [comment]
Saw this issue while looking for things to do, inspired me to write this: 
https://github.com/GhostRain0/SwpTestsGBA

TL;DR: The SWP opcode does in fact lock the bus. There's a more in-depth explanation in the README.

I have no idea how to implement this in an emulator without a performance impact, but hopefully it's negligible heh.

**Comment by fleroviux** [comment]
Thanks for the test! I just implemented this as it was very easy to do now, after refactoring my code for DMA interleaving the CPU mid-instruction.
