### ISSUE TITLE
Sweep shift seems to be wrong

### ISSUE THREAD

**Issue by gdkchan** [nba-emu/nanoboyadvance#18]
The formula for calculating the increment/decrement of the frequency with the shift value is usually:
`f +-= f / (2 ^ shift)`

Since this is a power of two, we could just use a shift instead, it would be:
`f +-= f / (1 << shift)`

However, in your code you seems to be shifting 2 which seems wrong:
https://github.com/nba-emu/nanoboyadvance/blob/b53bd2dc736306f7f7af9e9e0a95edcef852f282/src/gba/audio/quadchannel.cpp#L53

Because 2 ^ 0 = 1, 2 ^ 1 = 2 and so on...

It's also possible to just right shift it, which is what the Gameboy does I believe:
`f +-= f >> shift`

**Comment by fredericmeyer** [comment]
Oh snap, I must've been brain afk there! Thanks for your bug report x3
I'll fix this as fast as possible!

**Comment by fredericmeyer** [comment]
Should be fixed now :)

**Comment by gdkchan** [comment]
To test audio related stuff I recommend the demos on this page:
[http://belogic.com/gba/](http://belogic.com/gba/)

It allows to test each channel individually and change all the control settings, so you can compare the sound of your emulator with a real gba or other emulators.

About my projects: Thanks, althrough I will delete some of the old stuff soon. A lot of stuff there was sloppy coded.
