### ISSUE TITLE
Mac ARM64 native build

### ISSUE THREAD

**Issue by branchus** [nba-emu/NanoBoyAdvance#188]
Hi

I love NanoBoy advance a lot. recently upgraded to the new MacBook with M1, which is based on ARM64.

Just wondering, whether it is possible to have a native Mac ARM64 build? (Tried the nightly build, it is still intel x86_64 based)

Thanks
B

**Comment by fleroviux** [comment]
Hey, I'll look into it. I don't know if GitHub actions support M1 yet, or if it's necessary to use a different service. 
Worst-case I'll upload a M1 build myself as soon as 1.4 is out.

**Comment by branchus** [comment]
> Hey, I'll look into it. I don't know if GitHub actions support M1 yet, or if it's necessary to use a different service.
> Worst-case I'll upload a M1 build myself as soon as 1.4 is out.

Hi Fleroviux

Thank you for the quick response, and looking forward to try the Nanoboy Advance 1.4

Cheers
B

**Comment by fleroviux** [comment]
https://github.com/nba-emu/NanoBoyAdvance/releases/tag/v1.4

NanoBoyAdvance 1.4 is out now with a M1 build. Please feel free to reopen this issue if you have issues with it. Thanks.
