### ISSUE TITLE
LCD ghosting option with None color correction burns the first frame into the screen

### ISSUE THREAD

**Issue by testyourmine** [nba-emu/NanoBoyAdvance#191]
On the newest 1.4 release, when the LCD ghosting option is set to on, and the color correction is set to None, the first frame that appears is burnt into the screen, as so:
![image](https://user-images.githubusercontent.com/25854988/147002170-15cda1dc-673e-471e-8860-40b4271ce1ec.png)
![image](https://user-images.githubusercontent.com/25854988/147002848-bdae3316-9c46-4570-bf09-23e566a62b35.png)
This happens whether the filter is set to Nearest or Linear, but it works fine with xBRZ, even if color correction is None. It only acts like this for None color correction; when it's set to higan or GBA and any of the filters, it works as expected. I only tested a few games (Metroid: Zero Mission, Mario & Luigi: Superstar Saga, Pokémon Emerald), but it acts like this for all of them.

**Comment by fleroviux** [comment]
Sorry about that. I was sure I tested all the cases, but somehow broke this one in the end.
I have fixed it and updated the 1.4 release binaries.

Thanks for reporting.
