### ISSUE TITLE
Add save-path option

### ISSUE THREAD

**Issue by liberodark** [nba-emu/NanoBoyAdvance#199]
Hi

I have adding your emulator in a emulator OS beacause you have make a great work with NBA.
But we need a `--save-path` cli option and `save_path = "/"` toml option for save `.sav` to specific folder.
If you have time to check this feature that would be great.
Other little question : I'm using sdl build but have see a diff on 

**config.toml (sdl)** 

```
[video]
fullscreen = false
scale = 2
# Set empty string for no shader.
shader_vs = "shader/gba_colors.vs"
shader_fs = "shader/gba_colors.fs"
```

**config.toml (qt)**

```
[video]
fullscreen = false
scale = 2
filter = "linear"
color_correction = "agb"
lcd_ghosting = true
```

Is there a contraindication to using the sdl version ? 

Best Regards

**Comment by fleroviux** [comment]
Hello,

the SDL frontend is currently not up-to-date regarding options, as most effort has been spent on the new Qt UI.
Regarding the save path option: I'll consider adding it soon

**Comment by RokkumanX** [comment]
+1 for the ability to choose a custom save folder, this would be a very nice feature to have indeed!

**Comment by fleroviux** [comment]
The SDL version has been removed from the codebase for now, as it was more and more behind the Qt version in terms of capabilities. For the Qt version there's now an option in the configuration file in the latest nightly builds.
