### ISSUE TITLE
[Emulator detection] Inside-cap visual novel ports

### ISSUE THREAD

**Issue by fleroviux** [nba-emu/NanoBoyAdvance#203]
These games have an emulator detection mechanism that currently fails in NanoBoyAdvance.

See https://github.com/mgba-emu/mgba/issues/1815 for more information.

**Comment by skylersaleh** [comment]
I hear this game is broken on HW as well as it doesn't contain the proper nintendo logo to pass the boot ROM check.

**Comment by fleroviux** [comment]
It's possible to play them on real hardware using a flash cartridge or other tools to bypass the BIOS check. The issue was related to prefetch buffer emulation.
