### ISSUE TITLE
iOS/iPadOS version support?

### ISSUE THREAD

**Issue by francexecomb** [nba-emu/NanoBoyAdvance#209]
Hello is it possible to create an iOS/iPadOS version?

Currently I use an iPad Pro 11 inch with M1 chip and an iPhone 12 Pro both with jailbreak.

Can you create a .ipa file, thanks.

**Comment by fleroviux** [comment]
I don't own the hardware to properly develop for iOS/iPadOS atm and mobile ports are not in the project scope generally atm. Unless someone else wants to volunteer I'm going to close this for now.
