### ISSUE TITLE
Specification about file timestamp accuracy?

### ISSUE THREAD

**Issue by ghost** [nba-emu/NanoBoyAdvance#211]
Hi is there a file timestamp accuracy specification for save data? If so what is the correct behavior for the accuracy.

Currently I have these results.

Open a rom file for the first time. See the save data file timestamp info.

26 Apr 2022 08:37:10 - Created
26 Apr 2022 08:37:10 - Modified
26 Apr 2022 08:37:10 - Accessed

Then save manually in the game.

26 Apr 2022 08:37:10 - Created
26 Apr 2022 08:37:10 - Modified
26 Apr 2022 08:37:10 - Accessed

Close the emulator. As you can see, the Modified timestamp is only updated when the emulator is closed and not during the manual save in game.

26 Apr 2022 08:37:10 - Created
26 Apr 2022 08:45:51 - Modified
26 Apr 2022 08:45:51 - Accessed

**Comment by fleroviux** [comment]
This is because changes to the save data are lazily flushed to the filesystem when the emulator is closed (or a new ROM is opened) and is the intended behaviour. It has nothing to do with the accuracy of the emulator.
