### ISSUE TITLE
Compiling with all dlls embedded in exe

### ISSUE THREAD

**Issue by cedricwaltercson** [nba-emu/NanoBoyAdvance#213]
How do you compile the exe with all the dlls embedded?

**Comment by fleroviux** [comment]
Our CI already builds statically linked executables for Windows.
You can look at our [build.yml](https://github.com/nba-emu/NanoBoyAdvance/blob/master/.github/workflows/build.yml) for the commands / options that we use to build a statically linked executable.

Let me know if that works.

**Comment by cedricwaltercson** [comment]
Thank you for putting me in the right direction.
Please close the issue but I'll leave this here and this worked for me:

pacman -S --needed make mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-SDL2 mingw-w64-x86_64-glew mingw-w64-x86_64-qt5-static

It has to point to the qt5-static directory.

cmake \
            -B build \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-s" \
            -DPLATFORM_QT_STATIC=ON \
            -DSDL2_STATIC=ON \
            -DGLEW_USE_STATIC_LIBS=ON \
            -DQT5_STATIC_DIR="C:\msys64\mingw64\qt5-static"
          cd build
          make -j$NUMBER_OF_PROCESSORS

**Comment by cedricwaltercson** [comment]
Resolving..
