### ISSUE TITLE
No remapping for game controllers

### ISSUE THREAD

**Issue by Masaru2** [nba-emu/NanoBoyAdvance#216]
The title explains by itself.
You can remap the keyboard but you can't for game controllers
![image](https://user-images.githubusercontent.com/39504593/171044670-ae43f026-5c29-42ae-be01-a42b4cba8150.png)

**Comment by fleroviux** [comment]
![image](https://user-images.githubusercontent.com/13669774/172075269-7a73f295-6d06-4a91-a55e-66385c3c50cb.png)

This has been implemented now. You can remap the controller now, and also select which controller to use in the first place.
