### ISSUE TITLE
super mario advance dont work

### ISSUE THREAD

**Issue by mrdeathjr28** [nba-emu/NanoBoyAdvance#217]
super mario advance dont work and show this message:

![smadv1](https://user-images.githubusercontent.com/6601480/171298074-26a354bb-9c0e-446c-b5c1-713ec8efd158.png)

and show same error with any type of save, previously deleted save file

**Comment by fleroviux** [comment]
1. close the emulator
2. delete the save file
3. open the emulator
4. change save type to `EEPROM 512B`
5. open the game

The game should load normally now. after the new save has been created you should be able to set the save type back to `Detect`.

I am closing this in favor of issue #219
