### ISSUE TITLE
option to unlock aspect ratio

### ISSUE THREAD

**Issue by mrdeathjr28** [nba-emu/NanoBoyAdvance#218]
hi

maybe can add some option to unlock aspect ratio for delete black bars

thanks

**Comment by fleroviux** [comment]
I just implemented this option:
![image](https://user-images.githubusercontent.com/13669774/171480724-666c1f6e-5f04-4cfc-87bc-04abc1209d0e.png)

You'll be able to test it by download the nightly build once CI has completed running (in 15 minutes or so)
