### ISSUE TITLE
Large 2D sprites that use a tile index close to the right edge should wrap without advancing to next row

### ISSUE THREAD

**Issue by velipso** [nba-emu/NanoBoyAdvance#224]
NanoBoy Advance has the same issue I reported to mGBA, here:

https://github.com/mgba-emu/mgba/issues/2443

Here's the test ROM:

[obj.gba.zip](https://github.com/nba-emu/NanoBoyAdvance/files/8858056/obj.gba.zip)

Hardware displays white+green sprites, but NanoBoy displays white+red sprites.

**Comment by fleroviux** [comment]
Thanks for the bug report. I think I have a fix for this... will require thorough testing though.

**Comment by fleroviux** [comment]
First tests appear to indicate that things are working still. I'll merge the fix for now and probably test a bit more tomorrow.
