### ISSUE TITLE
NanoBoyAdvance won't actually load anything if the file path contains "foreign" characters

### ISSUE THREAD

**Issue by Bobsican** [nba-emu/NanoBoyAdvance#225]
If the filepath for a game or the bios involves navigating inside a folder path containing characters like "á" (aka, inside a folder named "á"), it'll just seemingly cancel the action silently then ask to do it again (if it's for the bios, or both), or give the message "Sorry, the specified ROM file cannot be located" (if this is only the case for the game file).
I was stuck for a while with this issue when I tried to set the bios file path so it could load it and all until I renamed the folders accordingly.

**Comment by fleroviux** [comment]
Can confirm. The code needs to be reworked slightly to use UTF-16 strings.

**Comment by wchisme2000** [comment]
Yes, Chinese path and file name do not work properly with the emulator...

**Comment by fleroviux** [comment]
@Bobsican @wchisme2000 This should now work properly in the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master). Can you confirm this?

**Comment by fleroviux** [comment]
Closing this now as there was no response and on my end the fix seems to work.
