### ISSUE TITLE
[Feature Request] Full-Screen by having a small window and black borders covering the rest of the screen

### ISSUE THREAD

**Issue by xZabuzax** [nba-emu/NanoBoyAdvance#249]
My biggest issue with this emulator so far is the full-screen option.

If I use Full-Screen it maximizes the whole window so it looks weird, I rather play in full screen but with an 3x window instead, in other words, have an 3x window while having black borders covering the rest of the screen, like VisualBoyAdvance-M. In fact, I'm still using VisualBoyAdvance-M because of it.

If this can be implemented then I will appreciate it! :)

**Comment by fleroviux** [comment]
This has been implemented. See Config >Window >Maximum scale to set a maximum size for the screen.
You can download the latest build [here](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master)

Please let me know if this works for you, so that I can close the issue.

**Comment by xZabuzax** [comment]
> This has been implemented. See `Config > Window > Maximum scale` to set a maximum size for the screen. You can download the latest build [here](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master)
> 
> Please let me know if this works for you, so that I can close the issue.

Excellent, thank you mate! I will test the new version a bit later today. I will let you know if it works :)

**Comment by xZabuzax** [comment]
> This has been implemented. See `Config > Window > Maximum scale` to set a maximum size for the screen. You can download the latest build [here](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master)
> 
> Please let me know if this works for you, so that I can close the issue.

Excellent! I just tried the newest version and this is exactly what I needed, thank you! if we could only hide the mouse cursor and remove that white line on top of the screen while in Full-screen then that would be even better! we are almost there!

If I may, I can offer a suggestion, I believe it's better to rename the "Maximum Scale" option to "Full-Screen Scale" or something like that, since this only works in full-screen then it needs to be more specific :)

This emulator is heading in the right direction so I will replace VisualBoyAdvance-M with this one pretty soon, I still like VisualBoyAdvance-M a lot since it offers a lot of configuration options, including hotkeys to configure the whole emulator (this includes Save/Load states) and all that which is nice.

I hope you take your time to implement those features as well, keep up the awesome work!

**Comment by fleroviux** [comment]
> If I may, I can offer a suggestion, I believe it's better to rename the "Maximum Scale" option to "Full-Screen Scale" or something like that, since this only works in full-screen then it needs to be more specific :)

The option also works outside of full-screen, it just generally limits the screen size. So calling it full-screen scale would be inaccurate.

Thanks for your feedback!
