### ISSUE TITLE
[Accuracy - Hardware?] Play Novel - Silent Hill (Japan and Translation v0.1)

### ISSUE THREAD

**Issue by minatogzenx** [nba-emu/NanoBoyAdvance#260]
When starting a new game the emulator hangs at the loading screen. This happens with both the original Japan release and the translation by [07151129](https://github.com/07151129/shpn_tool).
![imagen](https://user-images.githubusercontent.com/39786450/187385772-361060fb-eb57-4e1b-8b24-e856ed573428.png)
And if you try to load a save game on either version the game won't do it.
![imagen](https://user-images.githubusercontent.com/39786450/187386647-bc734668-493b-4cdf-8ca5-2ecd0ffeaae3.png)
![imagen](https://user-images.githubusercontent.com/39786450/187386973-25f1c9f2-1700-41fd-9c63-fb305a814d4c.png)
(The overlayed text on the translation seems to be a quirk of how it is implemented).

I tried to replicate this issue with VBA-M and mGBA, however those were able to boot and load a saved game.

Hope you're doing well, take care!

**Comment by fleroviux** [comment]
Weird. The game goes ingame for me. I'm able to load a save file as well.

What MD5 checksum does your Japan ROM have (you can check that [here](https://md5file.com/calculator))?
And are you using an original BIOS file or a replacement BIOS?
And did you change any of the default settings in NanoBoyAdvance?

![image](https://user-images.githubusercontent.com/13669774/187513673-750fbf96-6f84-4f93-87b5-d05f184ddd83.png)
You are supposed to press A (keyboard key A in NBAs default config) on that screen for it to continue.

**Comment by minatogzenx** [comment]
You're gonna kill me. The new settings overwrote my old keybindings :c

Sorry, closing it rn. I'll try to test a few other things once my Everdrive arrives. 

Btw, is there any way to donate or support the project?

**Comment by fleroviux** [comment]
I don't plan on taking donations at the moment.
