### ISSUE TITLE
GDB catches segfault on program load

### ISSUE THREAD

**Issue by LlamaTrauma** [nba-emu/NanoBoyAdvance#264]
After compiling NBA in MSYS2 in Windows 11 and running it with gdb, a segfault happens when loading a rom. It seems to be caused by vram_dirty_range_lo/hi in the ppu not getting explicitly initialized and being set to 0xBAADF00D (which seems like a Microsoft magic number, not sure if this means the issue is platform specific).

**Comment by fleroviux** [comment]
Sorry, for the late response. I just pushed a fix for this. Please let me know if it's fixed on your end as well.

**Comment by LlamaTrauma** [comment]
Looks like it is, thanks. I should clarify that the emulator still ran fine when run directly. I was wondering if this could be related to issue #259, but based on the wording it seems like it probably isn't. Thanks for the response!
