### ISSUE TITLE
Accuracy's doc is outdated plus version's numbers.

### ISSUE THREAD

**Issue by Felipefpl** [nba-emu/NanoBoyAdvance#272]
Aside being oudated the emulators described in the doc are missing their version's numbers: vba-m should stick to its latest official version 2.1.5 since this is easier to compare than a random weird combo of letters/numbers. Also, i dont know if the game's compatibility written below is outdated or not, perhaps it is.

https://github.com/nba-emu/NanoBoyAdvance/blob/master/docs/ACCURACY.md

**Comment by fleroviux** [comment]
VBA-M hasn't had an official stable release in years until recently, that's why I compared against a dev build (identified by the Git commit hash) for the comparison to be fair. I wasn't aware they released a new stable version recently. I'll probably update the table later today.

**Comment by Felipefpl** [comment]
I see, thanks for the update. Please, dont forget to show the numbers for nanoboy and skyemu since those are missing, this will help to choose the emulators. Also, mgba and ares' versions were updated. ;)

The test's suite of mgba was updated too:

https://github.com/mgba-emu/suite

**Comment by Felipefpl** [comment]
Thanks for the update of the accuracy doc, it's good to see how things are going for emulation now. :+1:
