### ISSUE TITLE
Issues compiling with all dlls in exe

### ISSUE THREAD

**Issue by evanft** [nba-emu/NanoBoyAdvance#273]
Hello,

I'm having an issue compiling with all the DLLs inside the exe. I was able to find issue #213 , which appears to be a similar issue to mine, but the solution doesn't work for me. When I use cmake commands to point to my qt5-static directory, I get the following response:

`CMake Warning:
  Manually-specified variables were not used by the project:
    QT5_STATIC_DIR`

My input into msys looks like this:

`$ cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-s" -DPLATFORM_QT_STATIC=ON -DSDL2_STATIC=ON -DGLEW_USE_STATIC_LIBS=ON -DQT5_STATIC_DIR="C:/msys64/mingw64/qt5-static"`

I know the QT5 static folder is in the correct location. I've also tried installing and reinstalling the libraries multiple times to no avail.

**Comment by fleroviux** [comment]
I can't check right now if I also get that warning or not. This should still build an executable. Does that executable have any dependencies, i.e. if you run it outside the Mingw-w64 bash, does it run (without manually copying the necessary DLLs)?

**Comment by evanft** [comment]
I just checked it. It does indeed create an executable, but it's only 5 MB. If I try to run it I get multiple missing DLL errors.  Copying those DLLs gets rid of those errors but the application still doesn't start.

**Comment by fleroviux** [comment]
I just successfully built a statically linked executable with this exact command:
```bash
$ cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-s" -DPLATFORM_QT_STATIC=ON -DSDL2_STATIC=ON -DGLEW_USE_STATIC_LIBS=ON -DQT5_STATIC_DIR="C:/msys64/mingw64/qt5-static"
```

It worked for me. Then I updated my MSYS2 using `pacman -Syu` to be sure and tried again and it still worked. Not sure why it's not working for you.

**Comment by evanft** [comment]
I'll give it a shot using the commands you listed and let you know what happens. If it works for you, then it's probably just something random on my end rather than anything inherent in your code. Or maybe I'm just an idiot and it's something really obvious I'm missing. Certainly wouldn't be the first time.

**Comment by evanft** [comment]
Ok so I tried this out.

On one of my machines it was able to build an exe file that was a little over 5 MB using the commands above. This exe runs fine on this machine. If I move it to a different machine, one that I don't use to do any software builds, I get the following error:

`This application failed to start because no Qt platform plugin could be initialised. Reinstalling the application may fix this problem.`

I'm investigating this issue right now, but so far nothing has fixed it.

**Comment by evanft** [comment]
I was just able to compile the exe and get a 24 MB file on my second machine. Very strange as I didn't do anything differently. I'll close the issue.
