### ISSUE TITLE
Discussion/Feature Request - Vulkan backend

### ISSUE THREAD

**Issue by branchus** [nba-emu/NanoBoyAdvance#277]
First it is a discussion. 
I saw in some other emulators for 3d games that they implemented Vulkan backend and seems there're benefits for graphic. But for GBA, not sure weather it is worth for it.

If there are benefits, is it possible to implement it please?

**Comment by fleroviux** [comment]
I don't think there's really a benefit for the basic 2D output with a couple of shaders we're doing. In any case it's not worth the effort and complexity that supporting Vulkan adds.
