### ISSUE TITLE
Mega Man Battle Network 1 - Title screen audio is distorted

### ISSUE THREAD

**Issue by Chariblaze** [nba-emu/NanoBoyAdvance#278]
The first half of the title screen music is normal, then the second half seems to get progressively higher-pitched, crackling a bit at the end.

Expected: https://www.youtube.com/watch?v=x7FU0QJ2KXA

NanoBoyAdvance Nightly (b818d31):

https://user-images.githubusercontent.com/25140801/219992112-b16ce55b-6342-4740-908f-53c4b75986d2.mp4

&nbsp;
Checking older versions, the pitch is correct in 1.3. If I tested correctly, it broke with e0d84dff7694b7dc1cdf096b113f53399d71f354.

**Comment by fleroviux** [comment]
Thanks for the bug report and tracking down the breaking commit for me! I think I have an idea why this is breaking and I'll try to fix it tonight.

**Comment by fleroviux** [comment]
The audio should now work correctly in the latest dev version. Thanks again for tracking down the breaking commit. That saved me a lot of time.
