### ISSUE TITLE
Levels fail to load with the color restoration mod of Super Mario Advance 4

### ISSUE THREAD

**Issue by Adamillo** [nba-emu/NanoBoyAdvance#282]
The levels load fine in open AGB firm on the 3DS so technically the game should run fine on real GBA hardware as well. Link to the ROM hack: https://www.romhacking.net/hacks/3315/
This was tested with the latest Nightly build

**Comment by fleroviux** [comment]
It appears that this hack does not like my Serial IO IRQ stub. When I remove the stub, the levels successfully load. 
This shouldn't be too difficult to fix - just needs some extra checks when the IRQ *really* should be asserted I think.

**Comment by Adamillo** [comment]
Awesome!
