### ISSUE TITLE
Sky effect in Harmony of Dissonance is slightly broken.

### ISSUE THREAD

**Issue by Michpem** [nba-emu/NanoBoyAdvance#284]
Hi there! I was playing through Castlevania Harmony of Dissonance and I found a (harmless) graphical bug with the sky effect in the Chapel of Dissonance. It seems like the background doesn't loop well in the emulator, which causes the clouds to not seamlessly connect in some areas and to have weird black bars.

Here's a (poorly recorded lol) .gif of how it looks:

https://cdn.discordapp.com/attachments/597986077197729803/1083140837216616579/Sky_Effect.gif

Also, it's a bit hard to fully see it because of the nature of the video (I grabbed the first one I found), but here's how the effect is supposed to look:

https://youtu.be/siIAivGSySs?t=7950

I know almost nothing about the GBA, but it may be a mode 7 issue? Also, if necessary, I'm on NBA 1.6.

**Comment by fleroviux** [comment]
Can you attach a save file (or if that's not possible a save state) please? I don't want to play through the game just so I can reproduce the issue. Thanks!

**Comment by Michpem** [comment]
Yeah for sure. Here it is: 

https://cdn.discordapp.com/attachments/597986077197729803/1083147760901038132/Castlevania_-_Harmony_of_Dissonance.sav

I was playing a randomizer, but I can confirm the save works with the vanilla ROM and that the graphical bug is also present there.

**Comment by Michpem** [comment]
Yep, it works just fine in the development build.

**Comment by fleroviux** [comment]
Alright! Thanks for confirming, I'll close the issue then.
