### ISSUE TITLE
Feature Request - Action Replay Code Support

### ISSUE THREAD

**Issue by AcerUp** [nba-emu/NanoBoyAdvance#289]
I understand that accuracy is the focus right now, but I was wondering if we could please have Action Replay and other forms of cheat code support in the future. This is an excellent emulator and AR/Gameshark code support would be a welcome addition.

**Comment by fleroviux** [comment]
Closing as duplicate because there's already an issue for cheat support: https://github.com/nba-emu/NanoBoyAdvance/issues/111
