### ISSUE TITLE
[Request] Widescreen/aspect ratio hack

### ISSUE THREAD

**Issue by Margen67** [nba-emu/NanoBoyAdvance#293]
See https://github.com/mgba-emu/mgba/issues/1960

**Comment by fleroviux** [comment]
This kind of hack is not compatible with the accurate cycle-by-cycle rendering that NanoBoyAdvance implements. Supporting this would require a second rendering path. Unless the scanline renderer comes back as a second option some day, this is considered out-of-scope/not planned for now.
