### ISSUE TITLE
All Fire Emblem games: Character portraits in dialogue have incorrect bottom row

### ISSUE THREAD

**Issue by PikaSamus** [nba-emu/NanoBoyAdvance#308]
It shows a duplicate of the second-to-last row on the graphic instead of the last row.
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/0fec62b2-7be6-4c60-8c87-f1e43b67d15a)
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/06acb146-88fc-42fe-b24a-c1d089ce5979)
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/13a5e248-f084-4200-9e55-595cf97e7fe5)

Compare ares:
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/ae7b68ae-cce2-4006-9c9c-ede66c59b1b5)
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/26789513-69bf-45e6-a500-b7054cff729d)
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/63016614/9cde3091-2785-4ca7-b892-f5c95ae5c603)

**Comment by fleroviux** [comment]
Hey @PikaSamus, thanks for the bug report. I have fixed a silly regression recently which I suspect should fix this issue.
Can you please the last [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master) and report if the issue still exists? Thanks.

**Comment by PikaSamus** [comment]
Oh yeah it is fixed there. Sorry for not checking dev build.

**Comment by fleroviux** [comment]
No worries!
