### ISSUE TITLE
When paused, toggling fast-forward hangs(?) the process

### ISSUE THREAD

**Issue by RetroEdit** [nba-emu/NanoBoyAdvance#310]
If `Input > Hold fast forward key` is unchecked, fast forward is currently active, and then the client is paused (I did `Ctrl+P`), the client becomes non-responsive if fast forward is toggled off (via spacebar). The menu still responds, but any attempts to unpause are ignored. Seems consistently reproducible.

Using NanoBoyAdvance 1.7.1 on Windows 11.

**Comment by fleroviux** [comment]
Thanks for the report, I can reproduce the issue on my side.

**Comment by fleroviux** [comment]
@RetroEdit this should be fixed now in the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master). Can you confirm that?

**Comment by RetroEdit** [comment]
Looks good to me.
