### ISSUE TITLE
Client unpauses upon game load

### ISSUE THREAD

**Issue by RetroEdit** [nba-emu/NanoBoyAdvance#313]
In other emulators, you can pause before you load a game, and it will stay paused, but NBA seems to override that option when a game is loaded.

Using NanoBoyAdvance 1.7.1 on Windows 11.

**Comment by fleroviux** [comment]
The current behavior is the intended one and was requested in the past

**Comment by RetroEdit** [comment]
Already said this in Discord, but I think it's worth repeating here: as I understand, the previous request was regarding the situation where a game is loaded and paused, and then the screen not changing when a new game is loaded.

This was an important issue to solve, but in my opinion, overriding pause is not the ideal solution. I think other emulators often solve this issue by refreshing the screen to blank when a new game is loaded to communicate the change.
