### ISSUE TITLE
Crackling noise randomly occurs, even during BIOS intro

### ISSUE THREAD

**Issue by RetroEdit** [nba-emu/NanoBoyAdvance#315]
I manually set `interpolate_fifo = false`, since I guess it was erroneously set to `true`. Both of the `hle` options are `false` as well.

https://www.youtube.com/watch?v=1Ut8RB_lMzg

Here's a video of starting up Shrek 2. On the first start, it had the issue, but when I reopened the game from `File > Recent`, it didn't happen. Overall, the crackling doesn't consistently happen when launching games, but it happens relatively often.

The specific pattern of distortions is relatively consistent when the distortion does occur.

## System environment
- NanoBoyAdvance e170695 on Windows 11

**Comment by fleroviux** [comment]
An attempt to fix this was made in https://github.com/nba-emu/NanoBoyAdvance/commit/86f7649540224cafd861ff15e496aaf5187c50ee.

**Comment by RetroEdit** [comment]
I downloaded 49c1403 and tested this a few dozen times, and it seems to be fixed.
