### ISSUE TITLE
Input dropping regression in 1.7.1

### ISSUE THREAD

**Issue by RetroEdit** [nba-emu/NanoBoyAdvance#321]
This was an issue I noticed when I was doing some speedrunning practice with NanoBoyAdvance, and other people on Discord were able to identify the issue and also confirm they were experiencing it. I wanted to file a ticket so it doesn't get accidentally forgotten about, since it's buried in a Discord conversation from 2023-07-30.

In my personal opinion, this being fixed might warrant a new patch release 1.7.2. I do understand the input handling code might be sensitive and there's no rush to fix this of course.

**Comment by fleroviux** [comment]
I haven't forgotten about it yet, but I do appreciate there being an issue for it! I have this at the back of my mind, but I haven't thought of a good way to implement the necessary changes yet.

**Comment by RetroEdit** [comment]
Promising result: after I tested [message-queue](https://github.com/nba-emu/NanoBoyAdvance/tree/message-queue) (specifically ff39a47159be8039a1d5ab2bbf5f8f534e6cd51c) by request, it seems like it might be resolved.

**Comment by RetroEdit** [comment]
With that merged in, it's now fixed in 1.8.0.
