### ISSUE TITLE
Timer disable/enable glitch

### ISSUE THREAD

**Issue by alyosha-tas** [nba-emu/NanoBoyAdvance#331]
It seems that when the timer is enabled, a timer tick happens before it is reset to the new reload value.

So if you are enabling the timer when it is previously disabled at 0xFFFF, it can overflow before being reset. In this case an interrupt can occur if they are enabled.

Emulating this fixes your 'cancel-irq-ie.gba' test.

A test rom demonstrating this is available here: https://github.com/alyosha-tas/gba-tests/blob/master/timer/timer_disable.gba

Works on GBP

**Comment by fleroviux** [comment]
Whoa, that makes a lot of sense in hindsight but I wouldn't have expected this to happen. Thanks for the test, I am passing it and my cancel-irq-ie.gba now.
