### ISSUE TITLE
DMG audio: Envelop step time lasts quite longer than it should

### ISSUE THREAD

**Issue by copyrat90** [nba-emu/NanoBoyAdvance#336]
# Issue

DMG audio: Envelop step time lasts quite longer than it should.
This is especially noticable on the shorter envelop.

## Test code & ROM
[env_len_test2.zip](https://github.com/nba-emu/NanoBoyAdvance/files/13371500/env_len_test2.zip)

### Hardware

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/b59486ae-ce85-460a-8bbe-384d433b2e42

### NanoBoyAdvance

https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/9bea4e0d-78fa-462f-a54c-e8cf0e98638b

### Comparison Images
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/ea9258bd-eeae-4e32-9bb9-dd6a2daee5d0)
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/c586fc82-3207-4cf0-845f-6306a6e5aea6)

**Comment by fleroviux** [comment]
I accidentally introduced a regression to envelope speed when I fixed the mid-note envelope divider change yesterday night. I just pushed a fix that *should* fix this while also not breaking the other tests. Can you confirm that this is the case?

**Comment by copyrat90** [comment]
Yeah, looks like it's fixed now, and it sounds OK for the previous 3 tests.

![image](https://github.com/nba-emu/NanoBoyAdvance/assets/34793045/485c66dd-5071-4993-914e-3ed759923152)

Thanks for the quick fix!
