### ISSUE TITLE
Background viewer: viewport horizontal position is fixed

### ISSUE THREAD

**Issue by Vulcalien** [nba-emu/NanoBoyAdvance#353]
I noticed that the red rectangle drawn to indicate the viewport of the background viewer seems to always have the same x coordinate, despite the background scrolling horizontally.

This is also shown in this example, in which scroll is 0, 0 but the rectangle is slightly moved to the right.
![example](https://github.com/nba-emu/NanoBoyAdvance/assets/47713809/b1524139-27c9-4e94-ae0e-e04ebf12575e)

**Comment by fleroviux** [comment]
Good catch! I introduced a typo while cleaning up the code last night. Thanks.

**Comment by Vulcalien** [comment]
I thought I was to late, but nice!
