### ISSUE TITLE
(v1.8.0) Bug: Shoulder button config (L or R) is reversed

### ISSUE THREAD

**Issue by RavenMacDaddy** [nba-emu/NanoBoyAdvance#355]
Whether I'm controlling it with a keyboard or a controller, while playing LoZ: The Minish Cap in this case, where R = Roll - it's the button that's configured as L in the emulator that corresponds to R in the game.

**Comment by fleroviux** [comment]
Looks like a typo slipped through during a recent input rework - I will push out updated executables as soon as I can.

**Comment by fleroviux** [comment]
I have updated the binaries on the releases page. Please redownload. The issue should be fixed.

**Comment by poesdelal** [comment]
Still reversed after redownload (with clean config.toml)

**Comment by poesdelal** [comment]
Just rechecked. I'm on Win10.
In dev build (master-00110ea) L and R works as intended.
In release 1.8.0 (exe CRC32=D957ED0D) it's reversed.
In both config.toml l=68 and r=70.

**Comment by fleroviux** [comment]
Weird, the CRC is correct. I have the same build running locally and the L/R buttons work as intended. I also haven't made any further adjustments to input since that singular fix.

**Comment by fleroviux** [comment]
Maybe try running https://github.com/shonumi/Emu-Docs/raw/master/GameBoy%20Advance/test_roms/tonc_gba_demos/key_demo.gba and check if it is really reversed and also attach a screenshot of your Input Config dialog.

**Comment by poesdelal** [comment]
![Nano-LR](https://github.com/nba-emu/NanoBoyAdvance/assets/51426037/5f1e6244-bbf3-4344-881f-51b939fbed83)
