### ISSUE TITLE
fullscreen mode has white bar alone sides of screen

### ISSUE THREAD

**Issue by kamikazilucas** [nba-emu/NanoBoyAdvance#363]
when i go fullscreen there appears a white bar across the sides of the screen which is annoying 
![image](https://github.com/nba-emu/NanoBoyAdvance/assets/20354993/e4e39308-6378-4a70-9345-d425cf03f086)

**Comment by fleroviux** [comment]
This is a duplicate of https://github.com/nba-emu/NanoBoyAdvance/issues/253
