### ISSUE TITLE
Star Wars Episode II - Attack Of The Clones (U) graphical glitches

### ISSUE THREAD

**Issue by benderscruffy** [nba-emu/NanoBoyAdvance#93]
during the intro when the words are scrolling up
in the first pic black line through the words "solar systems have declared"
in the next pic glitchy yellow line under the words "under the leadership of the"
![star](https://user-images.githubusercontent.com/2696404/81909561-5abfb880-95fd-11ea-9ec7-f9567626555e.PNG)
![star1](https://user-images.githubusercontent.com/2696404/81909565-5bf0e580-95fd-11ea-8e79-850791d6ec12.PNG)

**Comment by fleroviux** [comment]
Can confirm.

**Comment by wwark** [comment]
For information, I have this issue on my GBA SP (less visible on GBA SP screen but it is presents)
I can make a footage if needed.
Thanks,

**Comment by fleroviux** [comment]
@wwark Interesting. No need to provide footage, will compare against 3DS virtual console (should give best visual quality)

**Comment by fleroviux** [comment]
Can confirm that the artifact in the second picture also exists on hardware too.
